# https://github.com/gohugoio/hugoThemes#themetoml

name = "Book Too"
license = "MIT"
licenselink = "https://github.com/egenn/hugo-booktoo/blob/master/LICENSE"
description = "Hugo documentation theme as simple as plain book"
homepage = "https://github.com/egenn/hugo-booktoo"
tags = ["responsive", "clean", "documentation", "docs", "flexbox", "search", "mobile", "multilingual", "disqus"]
features = []
min_version = "0.68"

[author]
  name = "EDG"
  homepage = "https://github.com/egenn/"
